USE [VCDWH]
GO

-- =============================================
-- Author: ebp Global
-- Create date: 14/9/2017
-- Description:	Create PDAS system key.
-- =============================================
ALTER PROCEDURE [dbo].[proc_pdas_footwear_vans_create_copy_previous_release]
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE	@pdasid int = (SELECT MAX([id]) FROM [dbo].[dim_pdas])
	DECLARE @previous_pdasid int = (SELECT MAX([id]) FROM [dbo].[dim_pdas] WHERE [id] < @pdasid)

	IF @previous_pdasid IS NOT NULL
	BEGIN

		INSERT INTO [dbo].[fact_demand_total]
		(
			[dim_pdas_id]
	      ,[dim_business_id]
	      ,[dim_buying_program_id]
	      ,[dim_product_id]
	      ,[dim_date_id]
	      ,[dim_date_id_buy_month]
	      ,[dim_date_id_forecast_vs_actual]
	      ,[dim_factory_id_original_unconstrained]
	      ,[dim_factory_id_original_constrained]
	      ,[dim_factory_id]
	      ,[dim_factory_id_final]
	      ,[dim_customer_id]
	      ,[dim_demand_category_id]
	      ,[order_number]
	      ,[pr_code]
	      ,[pr_cut_code]
	      ,[po_code_customer]
	      ,[so_code]
	      ,[is_asap]
	      ,[quantity_lum]
	      ,[quantity_non_lum]
	      ,[quantity_unconsumed]
	      ,[quantity]
	      ,[quantity_region_mtl_lvl]
	      ,[quantity_customer_mtl_lvl]
	      ,[comment_vfa]
	      ,[edit_dt]
	      ,[allocation_logic_unconstrained]
	      ,[allocation_logic_constrained]
	      ,[customer_moq]
	      ,[customer_below_moq]
	      ,[region_moq]
	      ,[region_below_moq]
	      ,[upcharge]
	      ,[is_rejected]
	      ,[material_id_sr]
	      ,[component_factory_short_name]
	      ,[production_lt_actual_buy]
	      ,[production_lt_actual_vendor]
	      ,[comment_region]
	      ,[sold_to_customer_name]
	      ,[mcq]
	      ,[musical_cnt]
	      ,[delivery_d]
	      ,[confirmed_price_in_solid_size]
	      ,[fabriq_moq]
	      ,[confirmed_crd_dt]
	      ,[confirmed_unit_price_memo]
	      ,[confirmed_unit_price_po]
	      ,[cy_csf_load]
	      ,[min_surcharge]
	      ,[confirmed_unit_price_vendor]
	      ,[nominated_supplier_name]
	      ,[comment_vendor]
	      ,[confirmed_comp_eta_hk]
	      ,[comment_comp_factory]
	      ,[buy_comment]
	      ,[status_orig_req]
	      ,[performance_orig_req]
	      ,[smu]
	      ,[order_reference]
	      ,[sku_footlocker]
	      ,[prepack_code]
	      ,[exp_delivery_with_constraint]
	      ,[exp_delivery_without_constraint]
	      ,[coo]
	      ,[remarks_region]
	      ,[is_from_previous_release]
	      ,[source_system]
		)
		SELECT [dim_pdas_id]
		  ,[dim_business_id]
		  ,[dim_buying_program_id]
		  ,[dim_product_id]
		  ,[dim_date_id]
		  ,[dim_date_id_buy_month]
		  ,[dim_date_id_forecast_vs_actual]
		  ,[dim_factory_id_original_unconstrained]
		  ,[dim_factory_id_original_constrained]
		  ,[dim_factory_id]
		  ,[dim_factory_id_final]
		  ,[dim_customer_id]
		  ,[dim_demand_category_id]
		  ,[order_number]
		  ,[pr_code]
		  ,[pr_cut_code]
		  ,[po_code_customer]
		  ,[so_code]
		  ,[is_asap]
		  ,[quantity_lum]
		  ,[quantity_non_lum]
		  ,[quantity_unconsumed]
		  ,[quantity]
		  ,[quantity_region_mtl_lvl]
		  ,[quantity_customer_mtl_lvl]
		  ,[comment_vfa]
		  ,[edit_dt]
		  ,[allocation_logic_unconstrained]
		  ,[allocation_logic_constrained]
		  ,[customer_moq]
		  ,[customer_below_moq]
		  ,[region_moq]
		  ,[region_below_moq]
		  ,[upcharge]
		  ,[is_rejected]
		  ,[material_id_sr]
		  ,[component_factory_short_name]
		  ,[production_lt_actual_buy]
		  ,[production_lt_actual_vendor]
		  ,[comment_region]
		  ,[sold_to_customer_name]
		  ,[mcq]
		  ,[musical_cnt]
		  ,[delivery_d]
		  ,[confirmed_price_in_solid_size]
		  ,[fabriq_moq]
		  ,[confirmed_crd_dt]
		  ,[confirmed_unit_price_memo]
		  ,[confirmed_unit_price_po]
		  ,[cy_csf_load]
		  ,[min_surcharge]
		  ,[confirmed_unit_price_vendor]
		  ,[nominated_supplier_name]
		  ,[comment_vendor]
		  ,[confirmed_comp_eta_hk]
		  ,[comment_comp_factory]
		  ,[buy_comment]
		  ,[status_orig_req]
		  ,[performance_orig_req]
		  ,[smu]
		  ,[order_reference]
		  ,[sku_footlocker]
		  ,[prepack_code]
		  ,[exp_delivery_with_constraint]
		  ,[exp_delivery_without_constraint]
		  ,[coo]
		  ,[remarks_region]
		  ,1 AS [is_from_previous_release]
		  ,[source_system]
		FROM [dbo].[fact_demand_total]
		WHERE [dim_pdas_id] = @previous_pdasid
	END
END
